// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmNJoCzBu1dqTXNu4C20zYJ_AZr8zMnpg',
    appId: '1:586019743936:web:bb3bcf6af08ecf772f6525',
    messagingSenderId: '586019743936',
    projectId: 'animezone-e7102',
    authDomain: 'animezone-e7102.firebaseapp.com',
    storageBucket: 'animezone-e7102.appspot.com',
    measurementId: 'G-HE3XDKNWMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8nwOUC-yPanbo7P6SULs_xsO2_UrYeKk',
    appId: '1:586019743936:android:e8c5ec26bbffeafe2f6525',
    messagingSenderId: '586019743936',
    projectId: 'animezone-e7102',
    storageBucket: 'animezone-e7102.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs5MwV0EZxdN2Q2UWZC4GrHdoJP0zpM9g',
    appId: '1:586019743936:ios:86bca84fd4439bc32f6525',
    messagingSenderId: '586019743936',
    projectId: 'animezone-e7102',
    storageBucket: 'animezone-e7102.appspot.com',
    iosBundleId: 'com.example.animeZone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs5MwV0EZxdN2Q2UWZC4GrHdoJP0zpM9g',
    appId: '1:586019743936:ios:0af0bb5e2d56d2e12f6525',
    messagingSenderId: '586019743936',
    projectId: 'animezone-e7102',
    storageBucket: 'animezone-e7102.appspot.com',
    iosBundleId: 'com.example.animeZone.RunnerTests',
  );
}
